name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    # Documentation: https://github.com/zakodium/workflows#release
    uses: zakodium/workflows/.github/workflows/release.yml@release-v1
    permissions:
      packages: write
    with:
      npm: true
      public: false
      github-app-id: ${{ vars.RELEASE_APP_ID }}
    secrets:
      github-app-key: ${{ secrets.RELEASE_APP_KEY }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
